# Generated by Django 5.0.6 on 2024-06-29 14:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('date_registration', models.DateField(default=datetime.datetime(2024, 6, 29))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='Очень интересный товар')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date_add_product', models.DateField(default=datetime.datetime(2024, 6, 29))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_order', models.FloatField()),
                ('date_order', models.DateField(default=datetime.datetime(2024, 6, 29))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.client')),
                ('product', models.ForeignKey(default='пустота', on_delete=django.db.models.deletion.SET_DEFAULT, to='secondapp.product')),
            ],
        ),
    ]
