# Generated by Django 5.0.6 on 2024-06-29 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 20, 23, 20, 495780)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 20, 23, 20, 496305)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 20, 23, 20, 495780)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Пусто', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='secondapp.product'),
        ),
    ]
