# Generated by Django 5.0.6 on 2024-07-03 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_alter_client_date_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 19, 17, 2, 989878)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 19, 17, 2, 990371)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 19, 17, 2, 989878)),
        ),
    ]
