# Generated by Django 5.0.6 on 2024-07-05 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_alter_client_date_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='.media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 13, 55, 50, 764767)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 13, 55, 50, 765264)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 13, 55, 50, 765264)),
        ),
    ]
