# Generated by Django 5.0.6 on 2024-07-05 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_product_image_alter_client_date_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 14, 45, 42, 866286)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 14, 45, 42, 866782)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 14, 45, 42, 866782)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
